version: '3.8'

services:
  deb-builder:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - .:/workspace
      - package-build:/package
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    entrypoint: bash scripts/build.sh

volumes:
  package-build:
  node_modules: